use std::collections::HashMap;
use std::sync::{Arc, Mutex};

use runkon_flow::engine_error::EngineError;

use crate::workflow::item_provider::ItemProvider;

use super::bridge_lock_err;

/// Convert a conductor-core `FanOutItem` to a runkon-flow `FanOutItem`.
fn core_fan_out_item_to_rk(
    item: crate::workflow::item_provider::FanOutItem,
) -> runkon_flow::traits::item_provider::FanOutItem {
    runkon_flow::traits::item_provider::FanOutItem {
        item_type: item.item_type,
        item_id: item.item_id,
        item_ref: item.item_ref,
        context: item.context,
    }
}

/// Shared body for every `RkItemProvider::items()` implementation.
///
/// Locks the connection, delegates to `provider`, and maps the result back into
/// runkon-flow types.  All four adapters differ only in which `ItemProvider`
/// implementation they pass here.
pub(super) fn delegate_items<P: ItemProvider>(
    conn: &Arc<Mutex<rusqlite::Connection>>,
    config: &crate::config::Config,
    scope: Option<&dyn std::any::Any>,
    filter: &HashMap<String, String>,
    provider: P,
) -> Result<Vec<runkon_flow::traits::item_provider::FanOutItem>, EngineError> {
    let guard = conn.lock().map_err(bridge_lock_err)?;
    let core_ctx = crate::workflow::item_provider::ProviderContext {
        conn: &guard,
        config,
    };
    provider
        .items(&core_ctx, scope, filter)
        .map(|items: Vec<crate::workflow::item_provider::FanOutItem>| {
            items.into_iter().map(core_fan_out_item_to_rk).collect()
        })
        .map_err(EngineError::from)
}

// ---------------------------------------------------------------------------
// Rk*ItemProvider — one struct per item source, generated by macro.
//
// Both variants share the same ItemProvider impl body (delegate_items call).
// The only differences are: struct name, name() literal, optional repo_id
// field, and the inner provider constructed inside delegate_items.
// ---------------------------------------------------------------------------

// Shared ItemProvider trait impl — called from both branches of impl_rk_item_provider!.
// Each branch adds a private `fn provider(&self)` method to the struct so the inner
// provider can be obtained via `self.provider()` inside method bodies without needing
// `self` to appear in macro argument tokens (which Rust macro hygiene forbids).
macro_rules! impl_rk_item_provider_trait {
    ($name:ident, $provider_name:literal) => {
        impl runkon_flow::traits::item_provider::ItemProvider for $name {
            fn name(&self) -> &str {
                $provider_name
            }
            fn parse_scope(
                &self,
                raw: Option<&HashMap<String, String>>,
            ) -> Result<Option<Box<dyn std::any::Any>>, String> {
                self.provider().parse_scope(raw).map_err(|e| e.to_string())
            }
            fn scope_warnings(&self, raw: Option<&HashMap<String, String>>) -> Vec<String> {
                self.provider().scope_warnings(raw)
            }
            fn requires_filter(&self) -> bool {
                self.provider().requires_filter()
            }
            fn validate_filter(&self, filter: &HashMap<String, String>) -> Result<(), String> {
                self.provider()
                    .validate_filter(filter)
                    .map_err(|e| e.to_string())
            }
            fn items(
                &self,
                _ctx: &dyn runkon_flow::traits::run_context::RunContext,
                _info: &runkon_flow::traits::item_provider::ProviderInfo,
                scope: Option<&dyn std::any::Any>,
                filter: &HashMap<String, String>,
            ) -> Result<Vec<runkon_flow::traits::item_provider::FanOutItem>, EngineError> {
                delegate_items(&self.conn, &self.config, scope, filter, self.provider())
            }
            fn supports_ordered(&self) -> bool {
                self.provider().supports_ordered()
            }
            fn dependencies(&self, step_id: &str) -> Result<Vec<(String, String)>, EngineError> {
                let guard = self.conn.lock().map_err(bridge_lock_err)?;
                self.provider()
                    .dependencies(&guard, &self.config, step_id)
                    .map_err(EngineError::from)
            }
        }
    };
}

macro_rules! impl_rk_item_provider {
    // Variant: no extra field — inner provider needs no self data.
    ($name:ident, $provider_name:literal, $inner:expr) => {
        pub(crate) struct $name {
            conn: Arc<Mutex<rusqlite::Connection>>,
            config: crate::config::Config,
        }
        impl $name {
            pub(crate) fn new(
                conn: Arc<Mutex<rusqlite::Connection>>,
                config: crate::config::Config,
            ) -> Self {
                Self { conn, config }
            }
            fn provider(&self) -> impl ItemProvider {
                $inner
            }
        }
        impl_rk_item_provider_trait!($name, $provider_name);
    };
    // Variant: with repo_id — `$make_provider` is a closure `|repo_id| <expr>` that
    // receives `self.repo_id` and returns a provider.  Using a closure avoids any
    // direct reference to `self` at the macro call site (which is not a method scope).
    ($name:ident, $provider_name:literal, repo_id, $make_provider:expr) => {
        pub(crate) struct $name {
            conn: Arc<Mutex<rusqlite::Connection>>,
            config: crate::config::Config,
            repo_id: Option<String>,
        }
        impl $name {
            pub(crate) fn new(
                conn: Arc<Mutex<rusqlite::Connection>>,
                config: crate::config::Config,
                repo_id: Option<String>,
            ) -> Self {
                Self {
                    conn,
                    config,
                    repo_id,
                }
            }
            fn provider(&self) -> impl ItemProvider {
                ($make_provider)(self.repo_id.clone())
            }
        }
        impl_rk_item_provider_trait!($name, $provider_name);
    };
}

impl_rk_item_provider!(
    RkTicketsItemProvider,
    "tickets",
    repo_id,
    crate::workflow::item_provider::tickets::TicketsProvider::new
);

impl_rk_item_provider!(
    RkReposItemProvider,
    "repos",
    crate::workflow::item_provider::repos::ReposProvider
);

impl_rk_item_provider!(
    RkWorkflowRunsItemProvider,
    "workflow_runs",
    crate::workflow::item_provider::workflow_runs::WorkflowRunsProvider
);

// WorktreesProvider requires repo_id; worktree_id is not available in this context.
impl_rk_item_provider!(RkWorktreesItemProvider, "worktrees", repo_id, |repo_id| {
    crate::workflow::item_provider::worktrees::WorktreesProvider::new(repo_id, None)
});

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn delegate_items_propagates_mutex_poison() {
        let conn = Arc::new(Mutex::new(
            rusqlite::Connection::open_in_memory().expect("in-memory db"),
        ));
        // Poison the mutex by panicking inside a lock guard in another thread.
        let conn_clone = Arc::clone(&conn);
        let _ = std::thread::spawn(move || {
            let _guard = conn_clone.lock().unwrap();
            panic!("intentional panic to poison mutex");
        })
        .join();

        let config = crate::config::Config::default();
        let result = delegate_items(
            &conn,
            &config,
            None,
            &HashMap::new(),
            crate::workflow::item_provider::repos::ReposProvider,
        );
        match result {
            Err(e) => {
                let msg = e.to_string();
                assert!(
                    msg.contains("mutex poisoned"),
                    "expected poison error, got: {msg}"
                );
            }
            Ok(_) => panic!("expected mutex-poison error, got Ok"),
        }
    }

    #[test]
    fn rk_repos_item_provider_dependencies_returns_empty_for_nonexistent_step() {
        use runkon_flow::traits::item_provider::ItemProvider as RkItemProvider;

        let conn = Arc::new(Mutex::new(crate::test_helpers::setup_db()));
        let config = crate::config::Config::default();
        let provider = RkReposItemProvider::new(Arc::clone(&conn), config);

        let result = RkItemProvider::dependencies(&provider, "nonexistent-step");
        assert!(result.is_ok(), "dependencies should not error: {result:?}");
        assert!(
            result.unwrap().is_empty(),
            "dependencies for nonexistent step should be empty"
        );
    }
}
